### ISSUE TITLE
Compilation Failures when resolving from Service Graph

### ISSUE THREAD

**Issue by JaronrH** [JasperFx/lamar#73]
I'll apologize now -- I've been working on trying to figure this out for a while but still don't have much useful information to go off of!  

I've ran into a strange issue where I can't get my resolver to work in a console app.  Basically, I have a IFamilyPolicy to resolve some custom types for me using a factory.  This factory I need to pull from the container which I'm doing so like this:
```
var instance = serviceGraph.AllInstances().First(i => i.ServiceType == typeof(IBranchResolver));
var resolved = instance.Resolve(Scope.Empty());
```

This approach works in an xUnit Test (Core 2.1) and a sample project (Console Core 2.1) but not in my main project (again, Console Core 2.1).  I'm getting the following error back:         

```
An unhandled exception of type 'System.InvalidOperationException' occurred in Lamar.dll
Compilation failures!

CS0246: The type or namespace name 'DecisionTree' could not be found (are you missing a using directive or an assembly reference?)
CS0246: The type or namespace name 'DecisionTree' could not be found (are you missing a using directive or an assembly reference?)
CS0246: The type or namespace name 'DecisionTree' could not be found (are you missing a using directive or an assembly reference?)

Code:

using Lamar.IoC;
using System.Threading.Tasks;

namespace Jasper.Generated
{
    // START: DecisionTree_Interfaces_IBranchResolver_branchResolver
    public class DecisionTree_Interfaces_IBranchResolver_branchResolver : Lamar.IoC.Resolvers.SingletonResolver<DecisionTree.Interfaces.IBranchResolver>
    {
        private readonly Lamar.IoC.Scope _topLevelScope;

        public DecisionTree_Interfaces_IBranchResolver_branchResolver(Lamar.IoC.Scope topLevelScope) : base(topLevelScope)
        {
            _topLevelScope = topLevelScope;
        }



        public override DecisionTree.Interfaces.IBranchResolver Build(Lamar.IoC.Scope scope)
        {
            var container = (Lamar.IContainer) scope;
            return new DecisionTree.Lamar.BranchResolver(container);
        }

    }

    // END: DecisionTree_Interfaces_IBranchResolver_branchResolver
    
    
}
```

I do have NetStandard Assemblies that are similarly named/namespaced and I'm wondering if something is getting messed up in the parsing with Lamar as a result.  **DecisionTree**, which contains the **IBranchResolver** interface, and **DecisionTree.Lamar** which contains the implementation for **IBranchResolver** (**DecisionTree** is the core component while **DecisionTree.Lamar** adds support for Lamar).

Decisions.Lamar contains the ServiceRegistry that defines the IBranchResolver and adds the IFamilyPolicy's:
```
            For<IBranchResolver>().Use<BranchResolver>().Singleton();
            Policies.Add<TreeEnginePolicy>();
            Policies.Add<ExpressionEnginePolicy>();
```

Any ideas on where to look to solve this issue would be greatly appreciated!

(I did confirm that both assemblies were added to the Console project.)

**Comment by jeremydmiller** [comment]
So sorry, I just now saw this. Looking at it now....

**Comment by jeremydmiller** [comment]
Do me an oddball favor, rename your `DecisionTree.Lamar` assembly or namespace to `DecisionTreeLamar`and try again. But first, can you make sure you're on the latest greatest version? There was a similar issue we fixed a bit ago.

**Comment by JaronrH** [comment]
Sorry it took so long to get back to you!  Had a few medical issues that set me back.  Anyway, I updated to the latest version of Lamar and changed both the assembly and namespace to DecisionTreeLamar and tried my project again.  Unfortunately, I still get the same issue:


System.InvalidOperationException: 'Compilation failures!

CS0246: The type or namespace name 'DecisionTree' could not be found (are you missing a using directive or an assembly reference?)
CS0246: The type or namespace name 'DecisionTree' could not be found (are you missing a using directive or an assembly reference?)
CS0246: The type or namespace name 'DecisionTreeLamar' could not be found (are you missing a using directive or an assembly reference?)

Code:

using Lamar.IoC;
using System.Threading.Tasks;

namespace Jasper.Generated
{
    // START: DecisionTree_Interfaces_IBranchResolver_branchResolver
    public class DecisionTree_Interfaces_IBranchResolver_branchResolver : Lamar.IoC.Resolvers.SingletonResolver<DecisionTree.Interfaces.IBranchResolver>
    {
        private readonly Lamar.IoC.Scope _topLevelScope;

        public DecisionTree_Interfaces_IBranchResolver_branchResolver(Lamar.IoC.Scope topLevelScope) : base(topLevelScope)
        {
            _topLevelScope = topLevelScope;
        }



        public override DecisionTree.Interfaces.IBranchResolver Build(Lamar.IoC.Scope scope)
        {
            var container = (Lamar.IContainer) scope;
            return new DecisionTreeLamar.BranchResolver(container);
        }

    }

    // END: DecisionTree_Interfaces_IBranchResolver_branchResolver
    
    
}

**Comment by jeremydmiller** [comment]
@JaronrH Just coming back to this. I don't have any ideas here, but you could try to just paste the code into a real code file and see if that adds any insight. I actually don't think this is a Lamar issue per se but some kind of assembly binding problem

**Comment by JaronrH** [comment]
I actually ended up redesigning part of my application to work around the problem. I would be more then happy to roll back though and try this if you would like to get to the root of the problem!

**Comment by jeremydmiller** [comment]
Okay. Sorry, but without anything more concrete, I'm gonna close this one.

**Comment by aaw5017** [comment]
@jeremydmiller Just a heads up, I have a .NET 4.7.2 standard project and I'm having very similar issues.

I'm using Lamar as the DependencyResolver in a WebApi project, and all of my actual code compiles fine, but when I call `AssertConfigurationIsValid`, I get a bunch of errors relating to not being able to find the Lamar or System assemblies.

I have three Services that I'm mapping via my ServiceRegistry, all of which are producing similar results to this:

```
Error in new RecaptchaService()
System.InvalidOperationException: Compilation failures!

CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
CS0246: The type or namespace name 'Lamar' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Object' is not defined or imported
CS0518: Predefined type 'System.Object' is not defined or imported
CS0246: The type or namespace name 'Lamar' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Object' is not defined or imported
CS0115: 'Services_IRecaptchaService_recaptchaService.Build(Lamar.IoC.Scope)': no suitable method found to override
CS0518: Predefined type 'System.Object' is not defined or imported
CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Object' is not defined or imported
CS0246: The type or namespace name 'Services' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Void' is not defined or imported
CS0518: Predefined type 'System.Object' is not defined or imported
CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Object' is not defined or imported
CS0246: The type or namespace name 'Services' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Object' is not defined or imported
CS1955: Non-invocable member 'Services_IRecaptchaService_recaptchaService._func_of_IRecaptchaService' cannot be used like a method.

Code:

using System;
using System.Threading.Tasks;

namespace Jasper.Generated
{
   // START: Services_IRecaptchaService_recaptchaService
   public class Services_IRecaptchaService_recaptchaService : Lamar.IoC.Resolvers.TransientResolver<object>
   {
       private readonly System.Func<Services.IRecaptchaService> _func_of_IRecaptchaService;

       public Services_IRecaptchaService_recaptchaService(System.Func<Services.IRecaptchaService> func_of_IRecaptchaService)
       {
           _func_of_IRecaptchaService = func_of_IRecaptchaService;
       }



       public override object Build(Lamar.IoC.Scope scope)
       {
           return _func_of_IRecaptchaService();
       }

   }

   // END: Services_IRecaptchaService_recaptchaService
   
   
}


  at Lamar.Compilation.AssemblyGenerator.Generate(String code)
  at Lamar.Compilation.GeneratedAssembly.CompileAll(ServiceGraph services)
  at Lamar.IoC.Instances.GeneratedInstance.buildResolver(Scope scope)
  at Lamar.IoC.Instances.GeneratedInstance.Resolve(Scope scope)
  at Lamar.Container.buildAndValidateAll(StringWriter writer)
```

All of my code was working fine when using .NET 4.6.1, but things started to get wonky after the .NET framework upgrade. I'm using Lamar version 1.1.2 from NuGet.

My app is really simple, so if needed, I can provide all the code you need. Thanks in advance!

**Comment by CodingGorilla** [comment]
This seems like an odd error, how can it not find the `System` namespace?  Can you provide your code, or just your startup code, I'm curious how you're setting up Lamar.

**Comment by aaw5017** [comment]
Hi there and thanks for your quick reply!

A quick break down of how I'm running things in my app:

1) Main application is in its own project and has a Global.asax.cs file, which bootstraps the API configuration code within Application_Start

2) API is in its own project and exposes an App.Configure method, which wires up all the WebApi logic.

3) During API config, I'm setting WebApi's DependencyResolver to use Lamar IoC.

Here's the code where I set WebApi's resolver:

```
using Api.DependencyInjection;
using Lamar;
using System.Web.Http;

namespace Api.Config
{
    /// <summary>
    /// Dependency Injection Configuration
    /// </summary>
    internal static class DependencyInjectionConfig
    {
        /// <summary>
        /// Registration Method
        /// </summary>
        /// <param name="config"></param>
        public static void Register(HttpConfiguration config)
        {
            var container = new Container(new EPulseRegistry());

            /** This method invocation throws the huge error stack **/
            container.AssertConfigurationIsValid();

            config.DependencyResolver = new EPulseDependencyResolver(container);
        }
    }
}

```

Here's the ServiceRegistryCode

```
using Lamar;
using Services;

namespace Api.DependencyInjection
{
    /// <summary>
    /// An ExecutivePulse Service Registry
    /// </summary>
    public class EPulseRegistry : ServiceRegistry
    {
        public EPulseRegistry()
        {
            For<IRecaptchaService>().Use<RecaptchaService>();
            For<IMailerService>().Use<MailerService>();
            For<IValidationService>().Use<ValidationService>();
        }
    }
}

```

And finally, here's the DependencyResolver code, where the service resolution happens

```
using Lamar;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Http.Dependencies;

namespace Api.DependencyInjection
{
    /// <summary>
    /// A dependency scope
    /// </summary>
    public class EPulseDependencyScope : IDependencyScope
    {
        private INestedContainer _container;

        public EPulseDependencyScope(IContainer container)
        {
            _container = container.GetNestedContainer();
        }

        public void Dispose()
        {
            if (_container == null)
                return;

            _container.Dispose();
            _container = null;
        }

        public object GetService(Type serviceType)
        {
            if (serviceType == null)
                return null;

            if (serviceType.IsAbstract || serviceType.IsInterface)
                return _container.TryGetInstance(serviceType);

            return _container.GetInstance(serviceType);
        }

        public IEnumerable<object> GetServices(Type serviceType)
        {
            return _container.GetAllInstances(serviceType).Cast<object>();
        }
    }

    /// <summary>
    /// A dependency resolver
    /// </summary>
    public class EPulseDependencyResolver : EPulseDependencyScope, IDependencyResolver
    {
        private readonly IContainer _container;

        public EPulseDependencyResolver(IContainer container) : base(container)
        {
            _container = container;
        }

        public IDependencyScope BeginScope()
        {
            return new EPulseDependencyScope(_container);
        }
    }
}

```

I should note, this is very much copy/pasted code from an older project of mine using StructureMap. Like I mentioned earlier, things were working beautifully before my upgrade to .NET 4.7.2 for all my projects.

I'd love to know if I'm doing something incorrectly here.

Thanks again!

**Comment by CodingGorilla** [comment]
Out of curiosity, does it work properly if you don't do an `AssertConfigurationIsValid()`?  I know there has been some issues with that in the past, and TBH _I think_ it's a left over from StructureMap that should be removed since Lamar functions so much differently (but that's strictly my opinion).

**Comment by aaw5017** [comment]
Unfortunately, it does not. I get a different exception this time, relating to parameterless constructors

Here's a summary of the error output there

```
An error occurred when trying to create a controller of type 'EnvironmentController'. Make sure that the controller has a parameterless public constructor.

System.InvalidOperationException

at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)
at System.Web.Http.Dispatcher.HttpControllerDispatcher.d__15.MoveNext()

Compilation failures!

CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
CS0246: The type or namespace name 'Lamar' could not be found (are you missing a using directive or an assembly reference?)
CS0246: The type or namespace name 'Api' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Object' is not defined or imported
CS0246: The type or namespace name 'Lamar' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Object' is not defined or imported
CS0246: The type or namespace name 'Api' could not be found (are you missing a using directive or an assembly reference?)
CS0115: 'Api_Controllers_EnvironmentController_environmentController.Build(Lamar.IoC.Scope)': no suitable method found to override
CS0518: Predefined type 'System.Object' is not defined or imported
CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Object' is not defined or imported
CS0246: The type or namespace name 'Services' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Void' is not defined or imported
CS0518: Predefined type 'System.Object' is not defined or imported
CS0246: The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Object' is not defined or imported
CS0246: The type or namespace name 'Services' could not be found (are you missing a using directive or an assembly reference?)
CS0518: Predefined type 'System.Object' is not defined or imported
CS1955: Non-invocable member 'Api_Controllers_EnvironmentController_environmentController._func_of_IRecaptchaService' cannot be used like a method.
CS0518: Predefined type 'System.Object' is not defined or imported
CS0246: The type or namespace name 'Api' could not be found (are you missing a using directive or an assembly reference?)

Code:

using System;
using System.Threading.Tasks;

namespace Jasper.Generated
{
 // START: Api_Controllers_EnvironmentController_environmentController
 public class Api_Controllers_EnvironmentController_environmentController : Lamar.IoC.Resolvers.TransientResolver
 {
 private readonly System.Func _func_of_IRecaptchaService;

 public Api_Controllers_EnvironmentController_environmentController(System.Func func_of_IRecaptchaService)
 {
 _func_of_IRecaptchaService = func_of_IRecaptchaService;
 }



 public override Api.Controllers.EnvironmentController Build(Lamar.IoC.Scope scope)
 {
 var recaptchaService = _func_of_IRecaptchaService();
 return new Api.Controllers.EnvironmentController(recaptchaService);
 }

 }

 // END: Api_Controllers_EnvironmentController_environmentController
 
 
}

at Lamar.Compilation.AssemblyGenerator.Generate(String code)
 at Lamar.Compilation.GeneratedAssembly.CompileAll(ServiceGraph services)
 at Lamar.IoC.Instances.GeneratedInstance.buildResolver(Scope scope)
 at Lamar.IoC.Instances.GeneratedInstance.ToResolver(Scope topScope)
 at Lamar.ServiceGraph.FindResolver(Type serviceType)
 at Lamar.IoC.Scope.GetInstance(Type serviceType)
 at Api.DependencyInjection.EPulseDependencyScope.GetService(Type serviceType) in C:\\inetpub\\ExecutivePulse\\dotcom_server\\Api\\DependencyInjection\\EPulseDependencyResolver.cs:line 41
 at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.GetInstanceOrActivator(HttpRequestMessage request, Type controllerType, Func`1& activator)
 at System.Web.Http.Dispatcher.DefaultHttpControllerActivator.Create(HttpRequestMessage request, HttpControllerDescriptor controllerDescriptor, Type controllerType)
```

And my actual controller that it's bombing on looks like this

```
using Models.Validation;
using Services;
using System.Web.Http;

namespace Api.Controllers
{
    /// <summary>
    /// An environment controller
    /// </summary>
    [RoutePrefix("api/v1/env")]
    public class EnvironmentController : ApiController
    {
        /// <summary>
        /// A recaptcha service
        /// </summary>
        private readonly IRecaptchaService _recaptchaService;

        /// <summary>
        /// Ctor
        /// </summary>
        public EnvironmentController(IRecaptchaService recaptchaService)
        {
            _recaptchaService = recaptchaService;
        }

        /// <summary>
        /// Gets current environment object
        /// </summary>
        [HttpPost, Route("")]
        public IHttpActionResult GetEnv()
        {
            return Ok(new
            {
                RecaptchaSiteKey = _recaptchaService.GetSiteKey(),
                FormRegex = new
                {
                    Email = CommonRegex.EMAIL,
                    Phone = CommonRegex.PHONE
                }
            });
        }
    }
}
```

Just speculation, but something is _seemingly_ weird with the Jasper-generated code references.

Hopefully this sheds some light. If nothing else, I appreciate you taking the time to help with the issue!

**Comment by CodingGorilla** [comment]
Yea, it shouldn't be generating the constructor parameter as `System.Func`, there is no non-generic version of a `Func` so that's where the compiler errors are coming from.  Can you show the code for your `RecaptchaService` or at least the constructor?

**Comment by aaw5017** [comment]
HI again Mark,

I've listed both my recaptcha service interface and concrete type below.

__Interface__

```
namespace Services
{
    /// <summary>
    /// A recaptcha service contract
    /// </summary>
    public interface IRecaptchaService
    {
        /// <summary>
        /// Gets the recaptcha site key
        /// </summary>
        /// <returns></returns>
        string GetSiteKey();

        /// <summary>
        /// Determines whether a recaptcha submission is valid
        /// </summary>
        /// <remarks>Will throw a client exception if something goes wrong or is invalid</remarks>
        void Verify(string recaptchaResponse);
    }
}
```

__class__

```
using Models.Exceptions;
using Models.Recaptcha;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Configuration;
using System.Linq;
using System.Net;

namespace Services
{
    /// <summary>
    /// A recaptcha service
    /// </summary>
    internal class RecaptchaService : IRecaptchaService
    {
        private const string SITE_KEY = "RECAPTCHA_SITE_KEY";
        private const string SECRET_KEY = "RECAPTCHA_SECRET";

        string IRecaptchaService.GetSiteKey()
        {
            return ConfigurationManager.AppSettings[SITE_KEY];
        }

        void IRecaptchaService.Verify(string recaptchaResponse)
        {
            var resp = GetRecaptchaResponse(recaptchaResponse);

            if (!resp.IsSuccessful)
                throw new ClientException("The Google Recaptcha REST request was not successful.", "Our spam bot prevention service is currently unavailable. Please try your request again shortly.", HttpStatusCode.ServiceUnavailable);

            var respObj = JsonConvert.DeserializeObject<RecaptchaResponse>(resp.Content);
            if (respObj.Success && respObj.ErrorCodes.Count == 0)
                return;

            var errorCodes = string.Join(", ", respObj.ErrorCodes.Select(c => c));
            var msg = $"Recaptcha api response was not successful. Success flag was ${respObj.Success} and ErrorCodes were ${errorCodes}";

            throw new ClientException(msg, "Our Captcha service thinks you're a robot! If you're not a robot, please refresh the page and try again.", "Captcha Validation Failed", HttpStatusCode.BadRequest);
        }

        /// <summary>
        /// Submits an HTTP request to google for server-side recaptcha validation
        /// </summary>
        private IRestResponse GetRecaptchaResponse(string recaptchaResponse)
        {
            var secret = ConfigurationManager.AppSettings[SECRET_KEY];
            var client = new RestClient(new Uri("https://www.google.com/recaptcha/api"));

            // We must send the request params as part of the resource URL (i.e. as a query string)
            var body = $"secret={secret}&response={recaptchaResponse}";
            var resource = $"siteverify?{body}";
            var request = new RestRequest(resource, Method.POST);

            request.AddHeader("Content-Type", "application/x-www-formurlencoded; charset=utf-8");
            request.AddHeader("Accept", "application/json");

            return client.Execute(request);
        }
    }
}
```

**Comment by CodingGorilla** [comment]
Yea, I'm at a loss on this one.  I tried writing a unit test to reproduce this, and it works just fine.  Two things you can try: 1) Make your `RecaptchaService` public and see if that helps, 2) use your own lambda function to construct the `RecaptchaService`, like:

```
  For<IRecaptchaService>().Use(()=>new RecaptchaService());
```

I don't know if either of those will make any difference, again, because I can't seem to reproduce the issue.  If you can put together a simple test project that reproduces it, I'd be happy to run through it and try to figure out the problem.

**Comment by aaw5017** [comment]
Mark,

I've changed my DI library to Autofac for the time being to work around the issue. I have a feeling this is an issue with NuGet dependencies for .NET framework vs .NET Core, but I could be wrong.

Thanks for taking the time to try and remedy the situation!

**Comment by CodingGorilla** [comment]
I think you might be onto something there; I have a strict policy of not mixing .Net Core/Standard and .Net Framework, as so far it has been nothing but hell for me when I did.  Even though Standard is supposed to apply to the full framework, it created a nightmare of DLL hell issues for me when I tried it.

**Comment by jeremydmiller** [comment]
I'd honestly prefer to cut off support for any kind of .Net < netstandard2.0. We could try explicitly targeting .Net 4.7 as well to see if that helps w/ this kind of thing.

**Comment by CodingGorilla** [comment]
Except he said:
> things were working beautifully before my upgrade to .NET 4.7.2 for all my projects.

So was the problem related to 4.7.2?  But in general I would be on board with that idea.

**Comment by aaw5017** [comment]
I'm happy to blackbox test any pre-release code for you guys as well. Just let me know

**Comment by HamsterExAstris** [comment]
I'm also running into this, on ASP.NET/.NET Core 2.1 - it's failing to find a view model in the assembly containing the view. When using a model in a different assembly (admittedly, and namespace too), it worked fine.

> InvalidOperationException: Compilation failures!
> 
> CS0234: The type or namespace name 'ElectronUI' does not exist in the namespace 'ShatteredTemple.EbookArchiver' (are you missing an assembly reference?)
> CS0234: The type or namespace name 'ElectronUI' does not exist in the namespace 'ShatteredTemple.EbookArchiver' (are you missing an assembly reference?)
> CS0234: The type or namespace name 'ElectronUI' does not exist in the namespace 'ShatteredTemple.EbookArchiver' (are you missing an assembly reference?)
> 
> Code:

```csharp
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Mvc.ViewFeatures.Internal;
using System.Text.Encodings.Web;
using System.Threading.Tasks;

namespace Jasper.Generated
{
// START: Microsoft_AspNetCore_Mvc_Rendering_IHtmlHelper_System_Collections_Generic_IEnumerable_ShatteredTemple_EbookArchiver_ElectronUI_Models_Authors_AuthorViewModel___htmlHelper
public class Microsoft_AspNetCore_Mvc_Rendering_IHtmlHelper_System_Collections_Generic_IEnumerable_ShatteredTemple_EbookArchiver_ElectronUI_Models_Authors_AuthorViewModel___htmlHelper : Lamar.IoC.Resolvers.TransientResolver<Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<System.Collections.Generic.IEnumerable<ShatteredTemple.EbookArchiver.ElectronUI.Models.Authors.AuthorViewModel>>>
{
private readonly Microsoft.AspNetCore.Mvc.ViewFeatures.IHtmlGenerator _htmlGenerator;
private readonly Microsoft.AspNetCore.Mvc.ViewEngines.ICompositeViewEngine _compositeViewEngine;
private readonly Microsoft.AspNetCore.Mvc.ModelBinding.IModelMetadataProvider _modelMetadataProvider;
private readonly System.Text.Encodings.Web.HtmlEncoder _htmlEncoder;
private readonly System.Text.Encodings.Web.UrlEncoder _urlEncoder;
private readonly Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ExpressionTextCache _expressionTextCache;

public Microsoft_AspNetCore_Mvc_Rendering_IHtmlHelper_System_Collections_Generic_IEnumerable_ShatteredTemple_EbookArchiver_ElectronUI_Models_Authors_AuthorViewModel___htmlHelper(Microsoft.AspNetCore.Mvc.ViewFeatures.IHtmlGenerator htmlGenerator, Microsoft.AspNetCore.Mvc.ViewEngines.ICompositeViewEngine compositeViewEngine, Microsoft.AspNetCore.Mvc.ModelBinding.IModelMetadataProvider modelMetadataProvider, System.Text.Encodings.Web.HtmlEncoder htmlEncoder, System.Text.Encodings.Web.UrlEncoder urlEncoder, Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ExpressionTextCache expressionTextCache)
{
_htmlGenerator = htmlGenerator;
_compositeViewEngine = compositeViewEngine;
_modelMetadataProvider = modelMetadataProvider;
_htmlEncoder = htmlEncoder;
_urlEncoder = urlEncoder;
_expressionTextCache = expressionTextCache;
}



public override Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<System.Collections.Generic.IEnumerable<ShatteredTemple.EbookArchiver.ElectronUI.Models.Authors.AuthorViewModel>> Build(Lamar.IoC.Scope scope)
{
var memoryPoolViewBufferScope = scope.GetInstance<Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.IViewBufferScope>("memoryPoolViewBufferScope");
return new Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper<System.Collections.Generic.IEnumerable<ShatteredTemple.EbookArchiver.ElectronUI.Models.Authors.AuthorViewModel>>(_htmlGenerator, _compositeViewEngine, _modelMetadataProvider, memoryPoolViewBufferScope, _htmlEncoder, _urlEncoder, _expressionTextCache);
}

}

// END: Microsoft_AspNetCore_Mvc_Rendering_IHtmlHelper_System_Collections_Generic_IEnumerable_ShatteredTemple_EbookArchiver_ElectronUI_Models_Authors_AuthorViewModel___htmlHelper


}
```

ZIP of a fairly minimal repro solution is here: [EbookArchiver.zip](https://github.com/JasperFx/lamar/files/2848484/EbookArchiver.zip)

**Comment by jeremydmiller** [comment]
@HamsterExAstris What version of Lamar are you using? There was a fix for something similar in Lamar 2.1.0.

**Comment by HamsterExAstris** [comment]
Sorry, edited that out on accident - this is with 2.1.0.

**Comment by jeremydmiller** [comment]
Can you start a new issue? Whatever this is you're hitting, it's new.
